name: Run clean repo tool

on:
  schedule:
    - cron: "0 1 1 * *" # Runs at 01:00, on day 1 of the month
  workflow_dispatch:

permissions:
  contents: read

jobs:
  clean-repo:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@cb605e52c26070c328afc4562f0b4ada7618a84e # v2.10.4
        with:
          egress-policy: audit

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      # Call clean repo
      - name: Clean repo
        id: clean-repo-step
        uses: dotnet/docs-tools/cleanrepo@main
        with:
          docfx_directory: "."
          articles_directory: "docs"
          media_directory: "docs"
          snippets_directory: "." # This includes the ./samples and ./docs directories, which both contain snippets.
          includes_directory: "includes"
          url_base_path: "/dotnet"
          delete: true
          orphaned_articles: true
          orphaned_images: true
          catalog_images: false
          orphaned_snippets: true
          orphaned_includes: true
          replace_redirects: true
          relative_links: true
          remove_hops: true

      # Create the PR for the work done by the "clean repo" tool
      - name: create-pull-request
        uses: peter-evans/create-pull-request@67ccf781d68cd99b580ae25a5c18a1cc84ffff1f
        with:
          branch: create-cleanrepo-pull-request/patch
          title: "Monthly chores: Automated repo cleanup"
          commit-message: "Bot ðŸ¤– generated CleanRepo tool run"
          body: "Find and delete orphaned articles, images, snippets, and include files. Remove redirection hops, update redirected links in articles, and replace site-relative links with file-relative links. Contributes to #..."
